{% set name = "e3nn-jax" %}
{% set version = "0.20.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7764edb99d19465e574a23857e5f97420b4d720f06ba8bc18a01f9f2b8301d1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - jax
    - jaxlib
    - sympy
    - numpy
    - attrs

test:
  imports:
    - e3nn_jax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://e3nn-jax.readthedocs.io
  summary: Equivariant convolutional neural networks for the group E(3) of 3 dimensional rotations, translations, and mirrors.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
