{% set name = "e3nn-jax" %}
{% set version = "0.20.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/e3nn_jax-{{ version }}.tar.gz
  sha256: 84b8ec4ecd652be301a6243c23ae715b10b4debf4969dfd09190fba4656212ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - jax
    - jaxlib
    - sympy
    - numpy
    - attrs

test:
  imports:
    - e3nn_jax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://e3nn-jax.readthedocs.io
  summary: Equivariant convolutional neural networks for the group E(3) of 3 dimensional rotations, translations, and mirrors.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
