{% set name = "e3nn-jax" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/e3nn_jax-{{ version }}.tar.gz
  sha256: 51fc0920bd2b5a91e2530de239936a2ee5ab53ff0cea70872cab612559a3d557

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jax
    - dm-haiku
    - optax
    - sympy
    - numpy
    - flax
    - tqdm

test:
  imports:
    - e3nn_jax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://e3nn.org
  summary: Equivariant convolutional neural networks for the group E(3) of 3 dimensional rotations, translations, and mirrors.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
