{% set name = "e3nn-jax" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/e3nn_jax-{{ version }}.tar.gz
  sha256: 12eda5812aa3f42374495f53a0cd68c8423343160f82efdb2828e6f8b4741ce4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jax
    - dm-haiku
    - optax
    - sympy
    - numpy

test:
  imports:
    - e3nn_jax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://e3nn.org
  summary: Equivariant convolutional neural networks for the group E(3) of 3 dimensional rotations, translations, and mirrors.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
