schema_version: 1

context:
  name: e3nn-jax
  version: "0.21.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: f912707bafaf7a9893f1d83ab2e319455e6fafaaa9da3b0c4e39de5c2accd934

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - jax
    - jaxlib
    - sympy
    - numpy
    - attrs

tests:
  - python:
      imports:
        - e3nn_jax
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Equivariant convolutional neural networks for the group E(3) of 3 dimensional rotations, translations, and mirrors.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://e3nn-jax.readthedocs.io

extra:
  recipe-maintainers:
    - jan-janssen
